# Generated by Django 2.1.8 on 2019-04-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payflowtransaction',
            name='pnref',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='Payflow transaction ID'),
        ),
        migrations.AlterField(
            model_name='payflowtransaction',
            name='ppref',
            field=models.CharField(max_length=32, null=True, verbose_name='Payment transaction ID'),
        ),
    ]
